### ISSUE TITLE
Editing a note doesn't work anymore in v0.25.5

### ISSUE THREAD

**Issue by stmichalke** [CarnetApp/CarnetNextcloud#224] opened 2024-07-31 19:04 UTC
**Describe the bug**
Carnet app displays the list of notes. Selecting one for editing doesn't load the note but the spinner forever.

From nextcloud.log:
{"reqId":"ZDhqyN33exPybcYmhoho","level":3,"time":"2024-07-31T17:52:23+00:00","remoteAddr":"<IP>","user":"<user>","app":"PHP","method":"GET","url":"/apps/carnet/keywordsdb/merge","message":"foreach() argument must be of type array|object, null given at <NCDir>/apps/carnet/lib/Controller/NoteController.php#361","userAgent":"Mozilla/5.0 (Android 14; Mobile; rv:128.0) Gecko/128.0 Firefox/128.0","version":"29.0.4.1","data":{"app":"PHP"}}

{"reqId":"ZDhqyN33exPybcYmhoho","level":3,"time":"2024-07-31T17:52:23+00:00","remoteAddr":"<IP>","user":"<user>","app":"index","method":"GET","url":"/apps/carnet/keywordsdb/merge","message":"array_push(): Argument #1 ($array) must be of type array, null given in file '<NCDir>/apps/carnet/lib/Controller/NoteController.php' line 370","userAgent":"Mozilla/5.0 (Android 14; Mobile; rv:128.0) Gecko/128.0 Firefox/128.0","version":"29.0.4.1","exception":{"Exception":"Exception","Message":"array_push(): Argument #1 ($array) must be of type array, null given in file '<NCDir>/apps/carnet/lib/Controller/NoteController.php' line 370","Code":0,"Trace":[{"file":"<NCDir>/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"<NCDir>/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"<NCDir>/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"<NCDir>/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"<NCDir>/lib/private/AppFramework/Http/Dispatcher.php","Line":170,"Previous":{"Exception":"TypeError","Message":"array_push(): Argument #1 ($array) must be of type array, null given","Code":0,"Trace":[{"file":"<NCDir>/apps/carnet/lib/Controller/NoteController.php","line":370,"function":"array_push","args":["*** sensitive parameters replaced ***"]},{"file":"<NCDir>/apps/carnet/lib/Controller/NoteController.php","line":403,"function":"mergeWithMyKeywordsDB","class":"OCA\\Carnet\\Controller\\NoteController","type":"->"},{"file":"<NCDir>/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"mergeKeywordsDB","class":"OCA\\Carnet\\Controller\\NoteController","type":"->"},{"file":"<NCDir>/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"<NCDir>/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"<NCDir>/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"<NCDir>/lib/base.php","line":1050,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"<NCDir>/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"<NCDir>/apps/carnet/lib/Controller/NoteController.php","Line":370},"message":"array_push(): Argument #1 ($array) must be of type array, null given in file '<NCDir>/apps/carnet/lib/Controller/NoteController.php' line 370","exception":{},"CustomMessage":"array_push(): Argument #1 ($array) must be of type array, null given in file '<NCDir>/apps/carnet/lib/Controller/NoteController.php' line 370"}}

**To Reproduce**
1. Open Carnet browser.
2. Select a note.
3. Press "Abort".

**Expected behavior**
The editor shoud be opened.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52
 - OS: Android 14
 - Browser Firefox 
 - Version 128.0

**Comment by PhieF** [comment] 2024-07-31 19:55
Can you see your keywords/labels on the left side of the screen when loading Carnet (before loading the editor) ?

**Comment by stmichalke** [comment] 2024-07-31 20:12
Yes, with v0.25.4 and v0.25.5.

**Comment by PhieF** [comment] 2024-07-31 20:22
and not loading with 0.25.5 only ?

I can't reproduce for now and I think the log is not relevant to the issue, you say it's spinning, might be a cache issue, can you try emptying your browser cache for your nextcloud server ? Or just try to load it in private mode to see if the problem comes from there

**Comment by PhieF** [comment] 2024-07-31 20:26
Other question: in Carnet settings, is preload editor enable ? 

what about "Use Markdown editor (beta) " ?

**Comment by stmichalke** [comment] 2024-07-31 20:51
I logged in as admin, who never used carnet before. Everything works fine. I thank you very much for your valuable work.

The problem seems to be that there is a note with a keyword which is tagged to that note but not shown in the keyword list. This keyword isn't available from the editor, too.

Maybe a glitch in an older version. I will try to fix the entry in oc_carnet_metadata.

**Comment by PhieF** [comment] 2024-08-01 09:27
@stmichalke I've pushed another update that might help, please tell me if it does

**Comment by stmichalke** [comment] 2024-08-01 10:18
There are still keywords which are in the DB and tagged to notes, but are not accessible both from the sidebar and the editor. Newly created keywords work as expected.

After all it turned out that a user script injected by ViolentMonkey caused Carnet to stop working. I've fixed that. It had to do with lazy-loading. I'm sorry for reporting before more thoroughly investigating.

**Comment by PhieF** [comment] 2024-08-01 14:51
no problem, thanks to you I've detected another loading issue that could happen in some corner cases

I will add a way to recreate keywords db, if  you see a not with the tag issue remove and re-add the keyword

**Comment by PhieF** [comment] 2024-08-04 23:00
I'm closing this for now, feel free to re-open !

**Closed by PhieF** 2024-08-04 23:00 UTC
Labels: bug
