### ISSUE TITLE
Did Nextcloud update (20.0.5) break Carnet?

### ISSUE THREAD

**Issue by pengonia** [CarnetApp/CarnetNextcloud#143] opened 2021-01-26 19:59 UTC
**Describe the bug**
Only able to install Carnet from source and then I just see a blank screen, not Carnet.

**To Reproduce**

1. Unable to install Carnet from the web-based App Store. Get "Could not extract app carnet".
2. Unable to install at command line with ``sudo -u www-data php ./occ app:install carnet``. Get "Could not extract app carnet".
3. Was able to install by downloading and installing the source:
```
cd /tmp
wget https://github.com/CarnetApp/CarnetNextcloud/archive/master.zip
unzip master.zip
mv CarnetNextcloud-master/ carnet
sudo chown -R www-data: carnet/
sudo mv carnet/ /var/www/html/apps/
cd /var/www/html
sudo -u www-data php ./occ app:enable carnet
```
but only get a blank screen. I did restart Apache for good measure.

**Expected behavior**
I expect the main screen with the fake notes.

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser Chrome
 - Version 87.0.4280.141

**Comment by tofublock** [comment] 2021-01-27 08:28
I see the same behaviour. "Could not extract app carnet" both from browser and occ.
I'm on a fresh install of NC20.0.6 witch Apache in Docker with a reverse proxy in front of it.
When I manually install from zip I get a blank page and the following exception in log:

{"reqId":"oy0ty2OLj23bcTtba0XY","level":3,"time":"2021-01-26T21:36:54+00:00","remoteAddr":"X.X.X.X","user":"X","app":"PHP","method":"GET","url":"/apps/carnet/","message":{"Exception":"Error","Message":"file_get_contents(/var/www/html/custom_apps/carnet/templates/CarnetElectron/index.html): failed to open stream: No such file or directory at /var/www/html/custom_apps/carnet/templates/index.php#10","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"file_get_contents(/var/www/html/custom_apps/carnet/templates/CarnetElectron/index.html): failed to open stream: No such file or directory","/var/www/html/custom_apps/carnet/templates/index.php",10,{"0":"And 10 more entries, set log level to debug to see all entries","file":"/var/www/html/custom_apps/carnet/templates/index.php","additionalParams":{"nc_version":20,"carnet_display_fullscreen":"no","app_version":"0.23.7"},"_":{"nc_version":20,"carnet_display_fullscreen":"no","app_version":"0.23.7","requesttoken":"j03bRguK7ieTTbeZ27ikp+QlJP1OmOBaG32j23g2a28=:4CuMIX/zuWXfPO3tr8iV8tEdasgi7I5uaUvTjyoDOhg="},"l":{"__class__":"OC\\L10N\\LazyL10N"},"theme":{"__class__":"OCP\\Defaults"}}]},{"file":"/var/www/html/custom_apps/carnet/templates/index.php","line":10,"function":"file_get_contents","args":["/var/www/html/custom_apps/carnet/templates/CarnetElectron/index.html"]},{"file":"/var/www/html/lib/private/Template/Base.php","line":178,"args":["/var/www/html/custom_apps/carnet/templates/index.php"],"function":"include"},{"file":"/var/www/html/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->","args":["/var/www/html/custom_apps/carnet/templates/index.php",{"nc_version":20,"carnet_display_fullscreen":"no","app_version":"0.23.7"}]},{"file":"/var/www/html/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[{"nc_version":20,"carnet_display_fullscreen":"no","app_version":"0.23.7"}]},{"file":"/var/www/html/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->","args":[{"nc_version":20,"carnet_display_fullscreen":"no","app_version":"0.23.7"}]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Carnet\\Controller\\PageController"},"index"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Carnet\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"carnet.page.index"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/carnet/"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.6.1","id":"60111e192d70c"}

Does anybody know more?

**Comment by tofublock** [comment] 2021-01-27 10:52
It would be cool to be able to install install through the app store. Could the submodule be the culprit here?

**Comment by zsmart** [comment] 2021-02-01 20:39
Same for me. I see the following stacktrace in the logs:

[settings] Error: Exception: Could not extract app carnet at <<closure>>

0. /data/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 445
   OC\Installer->downloadApp("carnet")
1. /data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Settings\Controller\AppSettingsController->enableApps(["carnet"], [])
2. /data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
3. /data/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
4. /data/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
5. /data/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/settings/apps/enable")
6. /data/nextcloud/index.php line 37
   OC::handleRequest()

**Comment by callahan22** [comment] 2021-02-09 13:23
To add to this...

**Describe the bug**
Failure to install. "An error occured during the request. Unable to proceed. Could not extract app carnet"

**To Reproduce**
Steps to reproduce the behavior:
1. Try to install the app from the App repo built into Nextcloud.

**Expected behavior**
The app installed.

**Desktop (please complete the following information):**
 - Docker running on Ubuntu 18.04LTS.
 - https://hub.docker.com/r/linuxserver/nextcloud
 - Browser: Brave/Chrome/Firefox (fails on all).
 - Nextcloud version: 20.0.7 / Carnet won't install so can't give you that version number :-)

Nextcloud log file:
`{"reqId":"DwV2UEu8EmnhSCMjjJhh","level":3,"time":"February 09, 2021 12:46:19","remoteAddr":"192.168.1.24","user":"user","app":"settings","method":"POST","url":"/settings/apps/enable","message":{"Exception":"Exception","Message":"Could not extract app carnet","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":445,"function":"downloadApp","class":"OC\\Installer","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/config/www/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/config/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/config/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/config/www/nextcloud/lib/private/Installer.php","Line":297,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36","version":"20.0.7.1"}`

**Comment by diqidoq** [comment] 2021-02-17 12:52
Possibly related -> https://github.com/CarnetApp/CarnetNextcloud/issues/145

**Comment by fuzz500** [comment] 2021-02-17 21:41
Carnet failed to install on NextCloud 20 via the App Store.

I did a fresh install of Ubuntu 20.04 on a Digital Ocean droplet. I did "snap install nextcloud". When I logged into the NextCloud as administrator, go to app store, select Carnet, got "Could not extract app carnet".

I did a new install of Ubuntu 20.04 did a "snap install nextcloud --channel=19/stable". logged in as admin, went to app store, select Carnet. Installed perfectly.

If you have an existing NC19 install, and do a snap upgrade to upgrade to NC20, and Carnet will still work. I did this on another machine. 

It would appear the problem is not with running the code on NC20, but *installing* on NC20.

**Comment by diqidoq** [comment] 2021-02-23 20:12
Good finding. +1 @fuzz500

**Comment by PhieF** [comment] 2021-02-24 19:07
It should install properly with latest carnet version ! :) if somebody wants to confirm

thanks for your reports and investigations !

**Comment by callahan22** [comment] 2021-02-24 19:29
It's alive!

All good. Thanks for resolving :-)

**Comment by PhieF** [comment] 2021-02-25 08:34
Haha sorry I didn't have time to work a lot on this

I'm closing this issue

**Closed by PhieF** 2021-02-25 08:34 UTC
